### ISSUE TITLE
Error @interval

### ISSUE THREAD

**Issue by jacobdab** [zhong317/spriter2spine#6]
Hello, I tried to convert spiner to spine and got this error when converting free example Grey Guy. Don't have any thing more.

Traceback (most recent call last):
  File "spriter2spine.py", line 920, in <module>
  File "spriter2spine.py", line 909, in main
  File "spriter2spine.py", line 868, in convert
  File "spriter2spine.py", line 113, in extract_spriter_data
KeyError: '@interval'
[16944] Failed to execute script spriter2spine

**Comment by zhong317** [comment]
Can you provide the "Grey Guy" file to help me troubleshoot the problem?
